name: Build, Deploy and Switch Blue-Green

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t julienloonict/ss-bg:latest ./Website
        docker push julienloonict/ss-bg:latest

  deploy-to-test:
    runs-on: tstserver
    needs: build-and-push

    steps:
    - name: Pull nieuwe image op SR-TST-01
      run: |
        docker pull julienloonict/ss-bg:latest
        docker stop test-website || true
        docker rm test-website || true
        docker run -d --name test-website -p 80:80 julienloonict/ss-bg:latest

    - name: Verify test environment
      run: |
        sleep 5
        curl -s http://localhost | grep "Green Environment" \
        && echo "Test environment deployed successfully." \
        || (echo "Test environment deployment failed." && exit 1)

  approval-step:
    runs-on: ubuntu-latest
    needs: deploy-to-test

    steps:
    - name: Await manual approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: julienloonict

  deploy-to-production:
    runs-on: tstserver
    needs: approval-step

    steps:
    - name: Pull nieuwe image op SR-NEW-01
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@192.168.1.17 \
        "docker pull julienloonict/ss-bg:latest && \
         docker stop website || true && \
         docker rm website || true && \
         docker run -d --name website -p 80:80 julienloonict/ss-bg:latest"

    - name: Switch HAProxy backend naar Green
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HAPROXY_HOST }} \
        "echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S bash /home/srvadmin/switch-blue-green-haproxy.sh green"

    - name: Restart HAProxy
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HAPROXY_HOST }} \
        "echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S systemctl restart haproxy.service"

    - name: Verify HAProxy switch
      run: |
        sleep 5
        curl -s http://${{ secrets.HAPROXY_HOST }} | grep "Green Environment" \
        && echo "HAProxy switched to green." \
        || (echo "HAProxy did not switch to green." && exit 1)